repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: local
  hooks:
  - id: black
    name: black
    entry: sh scripts/run-uv run --locked --extra tests black
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: sh scripts/run-uv run --locked --extra tests flake8 --config .flake8
    language: system
    types: [python]
  - id: isort
    name: isort
    entry: sh scripts/run-uv run --locked --extra tests isort --profile black
    language: system
    types: [python]
  - id: pylint
    name: pylint
    entry: make pylint
    language: system
    pass_filenames: false
    types: [python]
