[package]
name = "_noise"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module", "abi3"] }
rand = "0.9.1"
utils_lib = { path = "../utils_lib" }

[lib]
name = "_noise"
crate-type = ["cdylib"]
